spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: 123456

jpa:
  show-sql: true
  hibernate:
    ddl-auto: none

server:
  port: 8090
